name: Deploy to Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy Code to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
        cd /home/ec2-user/your-repo
        git pull origin main
        npm install
        pm2 restart your-app-name
        EOF